### ISSUE TITLE
Documentation on database structure

### ISSUE THREAD

**Issue by carlos-granados** [GoogleCloudPlatform/snapshot-debugger#125]
Is there some documentation on the Firebase database structure? I want to work on updating the PHP debugger agent to work with this new debugger and would need to know the details of the data that is saved there

**Comment by mctavish** [comment]
There isn't any documentation on the structure yet, but we can add that fairly quickly.

It's great to hear that you're interested in updating the PHP debugger agent to use the Firebase backend.  Is the intention to do this work on a fork of the PHP agent or the main repo?  I want to make sure that any teardown related to the deprecation of the Cloud Debugger API will not damage your efforts.

It's also worth noting that there is no [firebase-admin sdk](https://firebase.google.com/docs/admin/setup) for PHP, so you'd likely have to use the [REST api](https://firebase.google.com/docs/reference/rest/database).

**Comment by carlos-granados** [comment]
My plan was to create a fork of https://github.com/googleapis/google-cloud-php-debugger. I will then create a PR for this repo but hopefully if this gets removed the fork will remain.

Regarding access to Firebase I was planning to use https://github.com/kreait/firebase-php which seems to provide the needed functionality

**Comment by jasonborg** [comment]
Hi Carlos,

The DB layout is now documented in [snapshot-debugger/docs/SCHEMA.md](https://github.com/GoogleCloudPlatform/snapshot-debugger/blob/main/docs/SCHEMA.md). You may also find the Firebase DB client implementations of the other Snapshot Debugger agents helpful as a reference:

* [Java Agent Firebase Client](https://github.com/GoogleCloudPlatform/cloud-debug-java/blob/main/src/agent/internals/src/main/java/com/google/devtools/cdbg/debuglets/java/FirebaseClient.java)
* [Python Agent Firebase Client](https://github.com/GoogleCloudPlatform/cloud-debug-python/blob/main/src/googleclouddebugger/firebase_client.py)
* [Node.js Firebase Client](https://github.com/googleapis/cloud-debug-nodejs/blob/main/src/agent/firebase-controller.ts)

If you have any questions along the way or find some of the documentation unclear please let us know.

Regards,
Jason

**Comment by carlos-granados** [comment]
I created this PR to update the PHP agent so that it now connects to Firebase and is able to work with this tool. https://github.com/googleapis/google-cloud-php-debugger/pull/4
I do not have the time to complete this PR with tests and everything, so just adding this here for reference for now in case someone else needs it. If I find the time to complete the PR and make it mergeable in the future, I'll let you know

**Comment by mctavish** [comment]
Happy to hear that you were able to get it to work.  Hopefully that is useful for others in its current state.  I'll try to find somebody who can look at the PR from my side.

**Comment by mctavish** [comment]
Closing this as the database schema has been documented.
