### ISSUE TITLE
Improve clarity that is possible to use any Firebase RTDB region

### ISSUE THREAD

**Issue by DKbyo** [GoogleCloudPlatform/snapshot-debugger#134]
Some users might be confused that the `init` command can only be used on Firebase RTDB from `us-central1`. However is possible to use any database from any region since the `database_id` is globally unique.

We could improve the `--database_id` parameter help text mentioning any `database_id` that could be used from any region, if the user uses the `DATABASE_ID` from the `DATABASE_URL` patterns:

- DATABASE_ID.firebaseio.com
- DATABASE_ID.europe-west1.firebasedatabase.app
- DATABASE_ID.asia-southeast1.firebasedatabase.app

We could also change the undocumented `--location`  help text from `init` command to reflect that is used only to create a database if doesn't exist.

**Comment by mctavish** [comment]
Good feedback.  Feel free to open a PR, or I'll make the updates later this week.

**Comment by mctavish** [comment]
Just took a look at this and though there isn't any technical reason that I know of to not support regions other than `us-central1`, the `snapshot-dbg-cli init` command does not yet allow you to create a database in any of the other regions.

I'll take a look at adding that functionality; I believe that it is just a matter of plumbing the location from the flag through to the database creation, but there may be other implications that will complicate matters.
