### ISSUE TITLE
CLI: Add logpoint support

### ISSUE THREAD

**Issue by jasonborg** [GoogleCloudPlatform/snapshot-debugger#6]
Currently the CLI only supports snapshots, logpoint support still needs to be added.

**Comment by boroskoyo** [comment]
Hi @jasonborg , we are on our way to making Sidekick open-source. It is similar to snapshot debugger in many ways but it also has extra features like logpoint. If you wish you can check it out here : https://www.producthunt.com/upcoming/sidekick-open-source-collect-traces-and-generate-logs-on-demand-without-stopping-redeploying-your-applications It will be here in like 1-2 weeks.

**Comment by jasonborg** [comment]
This has actually been done for a while now. It was released in version 0.2.0 on Sept 13.
